# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dc_metro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod ‘AFNetworking’
  pod ‘MBProgressHUD’
  pod ‘BDBOAuth1Manager’
  # Pods for dc_metro

end
